### ISSUE TITLE
如何运行呀？

### ISSUE THREAD

**Issue by wuguangyu111** [liuxz1011/TodyNet#4]
大佬 我下载源码运行train.py 的时候报错FileNotFoundError: [Errno 2] No such file or directory: '../data/UCR/StandWalkJump/X_train.pt'、
运行run.sh也报错 大佬能解释一下嘛 可不可以给一个开始教程

**Comment by wuguangyu111** [comment]
对了 我用的是windows电脑 不知道是不是这个原因

**Comment by wuguangyu111** [comment]
好的 跑起来了 十分感谢

**Comment by liuxz1011** [comment]
> 好的 跑起来了 十分感谢

客气🤝
